<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ipc\\address' => '/Address.php',
                'ipc\\cart' => '/Cart.php',
                'ipc\\cartprojectionlistener' => '/CartProjectionListener.php',
                'ipc\\checkoutcommand' => '/CheckoutCommand.php',
                'ipc\\checkoutevent' => '/CheckoutEvent.php',
                'ipc\\checkoutid' => '/CheckoutId.php',
                'ipc\\checkoutservice' => '/CheckoutService.php',
                'ipc\\checkoutstarted' => '/CheckoutStarted.php',
                'ipc\\checkoutstarteddomainevent' => '/CheckoutStartedDomainEvent.php',
                'ipc\\checkoutstarthandler' => '/CheckoutStartHandler.php',
                'ipc\\commandlocator' => '/CommandLocator.php',
                'ipc\\dispatcher' => '/Dispatcher.php',
                'ipc\\dispatcherlocator' => '/DispatcherLocator.php',
                'ipc\\domainevent' => '/DomainEvent.php',
                'ipc\\eventpublisher' => '/EventPublisher.php',
                'ipc\\eventstore' => '/EventStore.php',
                'ipc\\handler' => '/Handler.php',
                'ipc\\listener' => '/Listener.php',
                'ipc\\nulldispatcher' => '/NulLDispatcher.php',
                'ipc\\setshippingaddress' => '/SetShippingAddress.php',
                'ipc\\setshippingaddresshandler' => '/SetShippingAddressHandler.php',
                'ipc\\shippingaddressset' => '/ShippingAddressSet.php',
                'ipc\\shippingaddresssetdomainevent' => '/ShippingAddressSetDomainEvent.php',
                'ipc\\simpledispatcher' => '/SimpleDispatcher.php',
                'ipc\\startcheckout' => '/StartCheckout.php',
                'renderer' => '/Renderer.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
